version: '2.1'
services:
  core:
    build:
      context: ./core
    restart: 'no'
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.balena-socket: '1'