version: '2.1'
services:
  core:
    build: ./core
    restart: 'no'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.balena-socket: '1'
